---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sso

resources:
  - authelia.externalsecret.yaml
  - authelia-ldap.externalsecret.yaml
  - authelia-oidc.externalsecret.yaml
  - authelia-oidc-jwt.issuer.yaml
  - authelia-smtp.externalsecret.yaml
  - sso.httproute.yaml
  - sso.tailscale.yaml

helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    releaseName: authelia
    version: 0.10.37
    valuesFile: authelia.helmvalues/default.yaml
    additionalValuesFiles:
      - authelia.helmvalues/hardened.yaml

configMapGenerator:
  - name: authelia-configuration
    files:
      - configuration.yaml=configurations/authelia.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
        value: /var/lib/authelia
    target:
      kind: Deployment
      name: authelia

  # Configure Longhorn recurring jobs on all PVCs
  - patch: |-
      - op: add
        path: /metadata/labels/recurring-job.longhorn.io~1source
        value: enabled
      - op: add
        path: /metadata/labels/recurring-job-group.longhorn.io~1auto-snapshots
        value: enabled
      - op: add
        path: /metadata/labels/recurring-job-group.longhorn.io~1daily
        value: enabled
      - op: add
        path: /metadata/labels/recurring-job-group.longhorn.io~1monthly
        value: enabled
      - op: add
        path: /metadata/labels/recurring-job-group.longhorn.io~1monthly-maintenance
        value: enabled
    target:
      kind: PersistentVolumeClaim
