---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases

resources:
  - apps.objectstore.yaml
  - apps.postgresql.yaml
  - apps.roles.externalsecret.yaml
  - security/
