---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: percona-mongodb-system

helmCharts:
  - name: psmdb-operator
    releaseName: psmdb-operator
    repo: https://percona.github.io/percona-helm-charts/
    version: 1.21.2
    includeCRDs: true
    valuesFile: default.helmvalues.yaml
