---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: newt-system

resources:
  - newt.externalsecret.yaml

  # Include security policies
  - security/

helmCharts:
  - name: newt
    repo: https://charts.fossorial.io
    version: 1.1.0
    releaseName: newt
    namespace: newt-system
    valuesInline:
      newtInstances:
        - name: "main-tunnel"
          auth:
            existingSecretName: "newt-credentials"
            keys:
              endpointKey: "PANGOLIN_ENDPOINT"
              idKey: "NEWT_ID"
              secretKey: "NEWT_SECRET"
          enabled: true

labels:
  - pairs:
      app.kubernetes.io/name: newt
    includeTemplates: true
    includeSelectors: true

images:
  # renovate: datasource=docker depName=docker.io/fosrl/newt
  - name: docker.io/fosrl/newt
    newTag: 1.9.0@sha256:22edec551d81c500a9a3c790a41cd8f7eada3b47ba0a31a187c80d61318e4cc6
