apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-credentials
spec:
  refreshInterval: 1h
  data:
    - secretKey: endpoint
      remoteRef:
        key: shared/third-parties/pangolin/newt/lungmen.akn
        property: endpoint
    - secretKey: token_id
      remoteRef:
        key: shared/third-parties/pangolin/newt/lungmen.akn
        property: token_id
    - secretKey: token_secret
      remoteRef:
        key: shared/third-parties/pangolin/newt/lungmen.akn
        property: token_secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    name: newt-credentials
    template:
      engineVersion: v2
      data:
        PANGOLIN_ENDPOINT: "{{ .endpoint }}"
        NEWT_ID: "{{ .token_id }}"
        NEWT_SECRET: "{{ .token_secret }}"
