---
# =============================================================================
# Role: kokoro â€” Handlers
# =============================================================================

- name: Restart Kokoro
  ansible.builtin.command: launchctl kickstart -k gui/{{ lookup('pipe', 'id -u') }}/sh.chezmoi.shodan.kokoro
