---
# =============================================================================
# Role: kokoro â€” Handlers
# =============================================================================

- name: Restart Kokoro
  become: true
  ansible.builtin.command: launchctl kickstart -k system/sh.chezmoi.shodan.kokoro
