---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg-system

helmCharts:
  - name: cloudnative-pg
    releaseName: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.26.0

resources:
  - # Install Barman Cloud CNPG-I plugin (v0.6.0)
    https://raw.githubusercontent.com/cloudnative-pg/plugin-barman-cloud/e0c8b64470cc31f36b0511b80bbac6ecaa8bd283/manifest.yaml
  - # Configure defaults for CloudNativePG
    ../../../../../../defaults/kubernetes/cloudnative-pg/kustomize
