---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-credentials
spec:
  data:
    - secretKey: postgresql_password
      remoteRef:
        key: lungmen.akn/open-webui/database/postgresql
        property: password
    - secretKey: sso_client_secret
      remoteRef:
        key: lungmen.akn/open-webui/auth/oidc-client
        property: client_secret
    - secretKey: secret_key
      remoteRef:
        key: lungmen.akn/open-webui/encryption/secret-key
        property: key
    - secretKey: searxng_secret_key
      remoteRef:
        key: lungmen.akn/searxng/encryption/secret-key
        property: key
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        username: open-webui
        password: "{{ .postgresql_password }}"
        database_url: "postgresql://open-webui:{{ .postgresql_password }}@postgres-apps-secured-rw.databases:5432/open-webui"
        sso_client_secret: "{{ .sso_client_secret }}"
        secret_key: "{{ .secret_key }}"
        searxng_secret_key: "{{ .searxng_secret_key }}"
