---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pangolin

labels:
  - pairs:
      app.kubernetes.io/name: pangolin
      app.kubernetes.io/component: application
    includeTemplates: true
    includeSelectors: true

resources:
  - pangolin-data.volume.yaml
  - pangolin-config.configmap.yaml
  - pangolin.deployment.yaml
  - pangolin.postgresql.yaml
  - pangolin.service.yaml
