---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actual-budget

labels:
  - pairs:
      app.kubernetes.io/name: actual-budget
    includeTemplates: true
    includeSelectors: true
  - pairs:
      app.kubernetes.io/instance: actual-budget
    includeTemplates: true
    includeSelectors: true
  - pairs:
      # renovate: datasource=docker depName=actualbudget/actual-server
      app.kubernetes.io/version: 25.12.0
    includeTemplates: true

resources:
  - actual-budget.configuration.externalsecret.yaml
  - actual-budget.httproute.yaml
  - actual-budget.statefulset.yaml
  - actual-budget.password.externalsecret.yaml
  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/actualbudget/actual-server
  - name: ghcr.io/actualbudget/actual-server
    newTag: "25.12.0"
  # renovate: datasource=docker depName=docker.io/jhonderson/actual-http-api
  - name: docker.io/jhonderson/actual-http-api
    newTag: "25.12.0"
