---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actual-budget

labels:
  - pairs:
      app.kubernetes.io/name: actual-budget
      app.kubernetes.io/instance: actual-budget
    includeTemplates: true
    includeSelectors: true

resources:
  - actual-budget.configuration.externalsecret.yaml
  - actual-budget.httproute.yaml
  - actual-budget.statefulset.yaml
  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/actualbudget/actual-server
  - name: ghcr.io/actualbudget/actual-server
    newTag: "26.2.0"
