---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin

labels:
  - pairs:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: jellyfin
    includeTemplates: true
    includeSelectors: true

resources:
  - jellyfin.httproute.yaml
  - jellyfin.statefulset.yaml
  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/jellyfin/jellyfin
  - name: ghcr.io/jellyfin/jellyfin
    newTag: 10.11.6
