apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  # OpenWebUI official Helm chart
  - name: open-webui
    releaseName: open-webui
    repo: https://helm.openwebui.com
    version: 12.0.1
    valuesFile: open-webui.helmvalues/default.yaml

resources:
  - open-webui.configuration.externalsecret.yaml
  - open-webui.httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: open-webui
    includeTemplates: true
    includeSelectors: true

images:
  # renovate: datasource=docker depName=ghcr.io/open-webui/open-webui
  - name: ghcr.io/open-webui/open-webui
    newTag: v0.8.5@sha256:2deb90b0423473d8f97febced2e62b8fd898aa3eb61877bb3aa336370214c258
