---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  # Plugin required for Tailscale to access TUN/TAP interfaces
  - ../../../../../../catalog/kustomize/tun-device-plugin

  # Import current CoreDNS with Tailscale configuration
  - https://raw.githubusercontent.com/chezmoidotsh/arcane/refs/heads/main/catalog/talos/manifests/coredns+tailscale/1.12.3.yaml

patches:
  # Replace the Magic DNS IP with the Tailscale nameserver deployed in the cluster
  - target:
      kind: Deployment
      name: coredns
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: 10.96.10.96
