---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault.clustersecretstore.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: external-secrets-system
      namespace: external-secrets-system
    unsetOnly: true
