---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-snapshot
spec:
  concurrency: 1
  cron: 0 * * * *
  groups:
    - default
    - hourly
  labels:
    snapshot.longhorn.io/type: hourly
  name: hourly-snapshot
  retain: 24
  task: snapshot
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
spec:
  concurrency: 1
  cron: 0 2 * * *
  groups:
    - daily
  labels:
    backup.longhorn.io/type: daily
  name: daily-backup
  retain: 7
  task: backup-force-create
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-backup
spec:
  concurrency: 1
  cron: 0 3 * * 0
  groups:
    - weekly
  labels:
    backup.longhorn.io/type: weekly
  name: weekly-backup
  retain: 8
  task: backup-force-create
  parameters:
    full-backup-interval: "4"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monthly-backup
spec:
  concurrency: 1
  cron: 0 4 1 * *
  groups:
    - monthly
  labels:
    backup.longhorn.io/type: monthly
  name: monthly-backup
  retain: 12
  task: backup-force-create
  parameters:
    full-backup-interval: "3"
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: monthly-fs-trim
spec:
  concurrency: 1
  cron: 0 5 1 * *
  groups:
    - default
    - monthly-maintenance
  labels:
    maintenance.longhorn.io/type: filesystem-trim
  name: monthly-fs-trim
  task: filesystem-trim
