---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - longhorn.externalsecret.yaml
  - longhorn.httproute.yaml
  - namespace.yaml
  - recurring-jobs/6h-snapshots.recurringjob.yaml
  - recurring-jobs/daily-backup.recurringjob.yaml
  - recurring-jobs/monthly-backup.recurringjob.yaml
  - recurring-jobs/monthly-fs-trim.recurringjob.yaml
  - recurring-jobs/weekly-backup.recurringjob.yaml
  - security

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: 1.11.0
    valuesFile: longhorn.helmvalues/default.yaml
