---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: silverbullet

labels:
  - pairs:
      app.kubernetes.io/name: silverbullet
      app.kubernetes.io/component: application
    includeTemplates: true
  - pairs:
      app.kubernetes.io/instance: silverbullet
    includeTemplates: true
    includeSelectors: true
  - pairs:
      # renovate: datasource=docker depName=docker.io/zefhemel/silverbullet
      app.kubernetes.io/version: 2.1.7
    includeTemplates: true

resources:
  - silverbullet.httproute.yaml
  - silverbullet.ingress.yaml
  - silverbullet.smb-storage.yaml
  - silverbullet.statefulset.yaml
  - security/

images:
  # renovate: datasource=docker depName=docker.io/zefhemel/silverbullet
  - name: docker.io/zefhemel/silverbullet
    newTag: "2.1.7"
