apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    policy.networking.k8s.io/description: |
      Allows Newt to access Linkding service.
  name: allow-newt-to-linkding
  namespace: newt-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: newt
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: linkding
            app.kubernetes.io/name: linkding
      toPorts:
        - ports:
            - port: "9090"
              protocol: TCP
