apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    policy.networking.k8s.io/description: |
      Allows Newt to access Immich service.
  name: allow-newt-to-immich
  namespace: newt-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: newt
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: immich
            app.kubernetes.io/name: immich
            app.kubernetes.io/component: server
      toPorts:
        - ports:
            - port: "2283"
              protocol: TCP
