---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.application.yaml
  - envoy-gateway.application.yaml
  - external-secrets.application.yaml
  - kyverno.application.yaml

  - applications-new.applicationset.yaml
  - applications.applicationset.yaml
  - system-new.applicationset.yaml
  - system.applicationset.yaml
