---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/description: |
      This ApplicationSet is responsible for automatically deploying all
      system applications and configurations inside the targeted cluster,
      depending on existing templates and cluster definitions.
  name: system
spec:
  # Always preserve Applications on deletion of ApplicationSet
  preserveResourcesOnDeletion: true

  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.ignoreDifferences
        - .spec.source.targetRevision
        - .spec.sources[].targetRevision
        - .spec.syncPolicy.automated
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list: { elements: [] } # NOTE: this list will be populated by the `seed` ApplicationSet with the cluster metadata
          - git:
              repoURL: https://github.com/chezmoidotsh/arcane.git
              revision: main
              directories:
                - path: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/*

                # Exclude all directories that will be used by `system-critical` applications
                - path: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/cert-manager
                  exclude: true
                - path: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/envoy-gateway
                  exclude: true
                - path: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/external-secrets
                  exclude: true
  template:
    metadata:
      annotations:
        # All system applications should be deployed first before any applications
        argocd.argoproj.io/sync-wave: "10"

        # Source reference for argocd-extension-application-map
        source-ref.argocd.argoproj.io/0.path: "{{ .path.path }}"
        source-ref.argocd.argoproj.io/0.repository-url: https://github.com/chezmoidotsh/arcane.git
        source-ref.argocd.argoproj.io/0.target-revision: main
      name: '{{ .path.basename | trimPrefix "*" }}'
    spec:
      destination:
        server: "{{ .server }}"
        namespace: '{{ .path.basename | trimPrefix "*" | trimSuffix "-system" }}-system'
      project: system
      sources:
        - repoURL: https://github.com/chezmoidotsh/arcane.git
          path: "{{ .path.path }}"
          targetRevision: main
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Delete=confirm
          - Prune=confirm
          - ServerSideApply=true
