---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/description: |
      This ApplicationSet is responsible for automatically deploying all
      system applications and configurations inside the targeted cluster,
      depending on existing templates and cluster definitions.
  name: system
spec:
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.ignoreDifferences
        - .spec.source.targetRevision
        - .spec.sources[].targetRevision
        - .spec.syncPolicy.automated
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        mergeKeys:
          - .key
        generators:
          # Directories
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/chezmoidotsh/arcane.git
                    revision: main
                    directories:
                      - path: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/*

                      # Exclude all directories that will are automatically managed by the cluster Application
                      - path: projects/*/src/infrastructure/kubernetes/cert-manager
                        exclude: true
                      - path: projects/*/src/infrastructure/kubernetes/envoy-gateway
                        exclude: true
                      - path: projects/*/src/infrastructure/kubernetes/external-secrets
                        exclude: true
                      - path: projects/*/src/infrastructure/kubernetes/kyverno
                        exclude: true
                - list:
                    elements:
                      - .key: "{{ .path.basename }}"
          # Files
          - matrix:
              generators:
                - git:
                    repoURL: https://github.com/chezmoidotsh/arcane.git
                    revision: main
                    files:
                      - path: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/*/.application.patch

                      # Exclude all files that will are automatically managed by the cluster Application
                      - path: projects/*/src/infrastructure/kubernetes/cert-manager/.application.patch
                        exclude: true
                      - path: projects/*/src/infrastructure/kubernetes/envoy-gateway/.application.patch
                        exclude: true
                      - path: projects/*/src/infrastructure/kubernetes/external-secrets/.application.patch
                        exclude: true
                      - path: projects/*/src/infrastructure/kubernetes/kyverno/.application.patch
                        exclude: true
                - list:
                    elements:
                      - .key: "{{ .path.basename }}"
  syncPolicy:
    # Always preserve Applications on deletion of ApplicationSet
    preserveResourcesOnDeletion: true
  template:
    metadata:
      annotations:
        # All system applications should be deployed first before any applications
        argocd.argoproj.io/sync-wave: "10"

        # Source reference for argocd-extension-application-map
        source-ref.argocd.argoproj.io/0.path: "{{ .path.path }}"
        source-ref.argocd.argoproj.io/0.repository-url: https://github.com/chezmoidotsh/arcane.git
        source-ref.argocd.argoproj.io/0.target-revision: main
      name: "{{ .path.basename }}"
    spec:
      # Destination: namespace is the application name
      destination:
        server: "{{ .server }}"
        namespace: '{{ .path.basename | trimSuffix "-system" }}-system'

      # Project: system AND CANNOT BE OVERRIDDEN via patchTemplate
      project: system

      # Source: application directory
      sources:
        - repoURL: https://github.com/chezmoidotsh/arcane.git
          path: "{{ .path.path }}"
          targetRevision: main

      # Sync Policy: disabled sync by default
      syncPolicy:
        automated:
          enabled: false # Enables automated syncing of the application ( true by default ).
          prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).

        syncOptions:
          - ApplyOutOfSyncOnly=false # Only sync out-of-sync resources, rather than applying every object in the application
          - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
          - Delete=confirm # Confirm before deleting resources
          - Prune=confirm # Confirm before pruning resources
          - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
          - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
          - Replace=false # Argo CD will use kubectl replace or kubectl create command to apply changes.
          - ServerSideApply=true # Enable server-side apply for resource reconciliation
          - SkipDryRunOnMissingResource=true # Allow skip dry run on missing resource
          - Validate=true # Enable server-side validation during sync

  templatePatch: |
    {{- if hasKey . "metadata" }}
    metadata:
    {{ .metadata | toYaml | indent 6 }}
    {{- end }}

    {{- if hasKey . "spec" }}
    spec:
    {{ .spec | toYaml | indent 6 }}
    {{- end }}
