---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases

resources:
  - network-policy.allow-mealie.yaml
  - network-policy.allow-open-webui.yaml
  - network-policy.allow-postgres-to-s3-backup.yaml
  - network-policy.allow-postgres-apps-secured-to-s3-backup.yaml
