apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
data:
  # ==========================================
  # General application
  # ==========================================

  HOST: "0.0.0.0"
  PORT: "3080"
  NO_INDEX: "true"
  NODE_ENV: "production"
  TRUST_PROXY: "1"

  # ==========================================
  # Domains
  # ==========================================

  DOMAIN_CLIENT: "https://librechat.chezmoi.sh"
  DOMAIN_SERVER: "https://librechat.chezmoi.sh"

  # ==========================================
  # Search (Meilisearch)
  # ==========================================

  SEARCH: "true"
  MEILI_NO_ANALYTICS: "true"
  MEILI_HOST: "http://librechat-meilisearch.open-webui.svc.cluster.local:7700"

  # ==========================================
  # RAG API
  # ==========================================

  RAG_API_URL: "http://librechat-rag-api.open-webui.svc.cluster.local:8000"

  # ==========================================
  # Authentication
  # ==========================================

  ALLOW_EMAIL_LOGIN: "true"
  ALLOW_REGISTRATION: "false"
  ALLOW_SOCIAL_LOGIN: "false"
  ALLOW_UNVERIFIED_EMAIL_LOGIN: "true"

  # ==========================================
  # Debug
  # ==========================================

  DEBUG_LOGGING: "true"
  DEBUG_CONSOLE: "true"

  # ==========================================
  # External LLM Authentication
  # ==========================================

  ANTHROPIC_API_KEY: user_provided
  ANYSCALE_API_KEY: user_provided
  APIPIE_API_KEY: user_provided
  COHERE_API_KEY: user_provided
  DATABRICKS_API_KEY: user_provided
  DEEPSEEK_API_KEY: user_provided
  FIREWORKS_API_KEY: user_provided
  FLUX_API_BASE_URL: user_provided
  GOOGLE_KEY: user_provided
  GROQ_API_KEY: user_provided
  HUGGINGFACE_TOKEN: user_provided
  MISTRAL_API_KEY: user_provided
  MISTRAL_API_KEY: user_provided
  OPENAI_API_KEY: user_provided
  OPENROUTER_KEY: user_provided
  PERPLEXITY_API_KEY: user_provided
  SHUTTLEAI_API_KEY: user_provided
  TOGETHERAI_API_KEY: user_provided
  UNIFY_API_KEY: user_provided
  XAI_API_KEY: user_provided
