apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - litellm.deployment.yaml
  - litellm.configuration.yaml
  - litellm.proxy-config.yaml
  - litellm.configuration.externalsecret.yaml
  - litellm.httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: litellm
    includeTemplates: true
    includeSelectors: true
  - pairs:
      # renovate: datasource=docker depName=ghcr.io/berriai/litellm-database
      app.kubernetes.io/version: main-v1.81.12-stable.2
    includeTemplates: true

images:
  # renovate: datasource=docker depName=ghcr.io/berriai/litellm-database
  - name: ghcr.io/berriai/litellm-database
    newTag: main-v1.81.12-stable.2@sha256:dabbc5368dccc272d8d5e3744fc58e696f58a072917ef8884a4d3a49fea5a33c
