apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - litellm.deployment.yaml
  - litellm.configuration.yaml
  - litellm.proxy-config.yaml
  - litellm.configuration.externalsecret.yaml
  - litellm.httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: litellm
    includeTemplates: true
    includeSelectors: true
  - pairs:
      # renovate: datasource=docker depName=ghcr.io/berriai/litellm-database
      app.kubernetes.io/version: main-v1.81.12-stable.2
    includeTemplates: true

images:
  # renovate: datasource=docker depName=ghcr.io/berriai/litellm-non_root
  - name: ghcr.io/berriai/litellm-non_root
    newTag: main-v1.81.12-stable.1@sha256:14a5421e1dd929bcc5952800b79e0d79633240fd166d01e775bdb44d9559c0cd
