---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-credentials
spec:
  data:
    - secretKey: postgresql_password
      remoteRef:
        key: lungmen.akn/litellm/database/postgresql
        property: password
    - secretKey: sso_client_id
      remoteRef:
        key: lungmen.akn/litellm/auth/oidc-client
        property: client_id
    - secretKey: sso_client_secret
      remoteRef:
        key: lungmen.akn/litellm/auth/oidc-client
        property: client_secret
    - secretKey: master_key
      remoteRef:
        key: lungmen.akn/litellm/encryption/master-key
        property: key
    - secretKey: salt_key
      remoteRef:
        key: lungmen.akn/litellm/encryption/salt-key
        property: key
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        DATABASE_URL: "postgresql://litellm:{{ .postgresql_password }}@postgres-apps-secured-rw.databases.svc.cluster.local:5432/litellm"
        GENERIC_CLIENT_ID: "{{ .sso_client_id }}"
        GENERIC_CLIENT_SECRET: "{{ .sso_client_secret }}"
        LITELLM_MASTER_KEY: "{{ .master_key }}"
        LITELLM_SALT_KEY: "{{ .salt_key }}"
