---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale-system

resources:
  # Required secrets and ProxyClass for Tailscale Operator
  - restricted.proxyclass.yaml
  - operator-oauth.externalsecret.yaml

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.94.2
    releaseName: tailscale-operator
    namespace: tailscale-system
    valuesFile: tailscale.helmvalues/default.yaml
    additionalValuesFiles:
      - tailscale.helmvalues/hardened.yaml
    valuesInline:
      operatorConfig:
        hostname: lungmen-akn
    includeCRDs: true
