---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-system

resources:
  # Project definition for ArgoCD applications
  - default.project.yaml

  # Application definitions
  - cert-manager.application.yaml
  - cloudnative-pg.application.yaml
