---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-system

resources:
  # Project definition for ArgoCD applications
  - default.project.yaml

  # - argocd.application.yaml
