---
# Pangolin Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pangolin
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pangolin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - Prune=confirm
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/chezmoidotsh/arcane.git
      path: projects/kazimierz.akn/src/apps/pangolin
      targetRevision: issue-458/prepare-kazimierz-pangolin
