---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default.gateway.yaml

  # (SecOps) Network Policies
  - security/allow-from-internal.networkpolicy.yaml
  - security/allow-to-cluster.networkpolicy.yaml
  - security/allow-to-kubernetes-api.networkpolicy.yaml
