---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pocket-id.authbackend.yaml
  - personal.mount.yaml
  - shared.mount.yaml

  # Additional policies
  - policies/personal-admin-access.yaml
  - policies/personal-user-access.yaml
  - policies/sso-admin-policy.yaml
