apiVersion: v1
kind: ConfigMap
metadata:
  name: firecrawl-config
data:
  HOST: "0.0.0.0"
  REDIS_URL: "redis://:redis@redis:6379"
  REDIS_RATE_LIMIT_URL: "redis://:redis@redis:6379"
  OPENAI_BASE_URL: "http://192.168.10.30:1234/v1"
  MODEL_NAME: "mistralai/ministral-3-3b"
  MODEL_EMBEDDING_NAME: "text-embedding-nomic-embed-text-v1.5"
  PLAYWRIGHT_MICROSERVICE_URL: "http://playwright-service:3000"
  USE_DB_AUTHENTICATION: "false"
  SENTRY_ENVIRONMENT: "production"
  ENV: "production"
  LOGGING_LEVEL: "DEBUG"
  IS_KUBERNETES: "true"
  NUQ_DATABASE_URL: "postgresql://postgres:password@nuq-postgres:5432/postgres"
