apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firecrawl-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: firecrawl-secret
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: firecrawl/OPENAI_API_KEY
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: firecrawl/SLACK_WEBHOOK_URL
    - secretKey: LLAMAPARSE_API_KEY
      remoteRef:
        key: firecrawl/LLAMAPARSE_API_KEY
    - secretKey: BULL_AUTH_KEY
      remoteRef:
        key: firecrawl/BULL_AUTH_KEY
    - secretKey: TEST_API_KEY
      remoteRef:
        key: firecrawl/TEST_API_KEY
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: firecrawl/REDIS_PASSWORD
