apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firecrawl-credentials
spec:
  data:
    - secretKey: postgresql_password
      remoteRef:
        key: lungmen.akn/firecrawl/database/postgresql
        property: password
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault.chezmoi.sh
  target:
    template:
      data:
        database_url: "postgresql://firecrawl:{{ .postgresql_password }}@postgres-apps-secured-rw.databases:5432/firecrawl"
