apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - firecrawl.configuration.yaml
  - firecrawl.api.yaml
  - firecrawl.worker.yaml
  - firecrawl.nuq-worker.yaml
  - firecrawl.playwright.yaml
  - firecrawl.redis.yaml
  - firecrawl.searxng.yaml
  - firecrawl.nuq-postgres.yaml

labels:
  - pairs:
      app.kubernetes.io/name: firecrawl
      app.kubernetes.io/instance: firecrawl
    includeTemplates: true
    includeSelectors: true
