---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: valkey
    releaseName: valkey
    repo: https://valkey-io.github.io/valkey-helm/
    version: 0.9.3
    valuesFile: valkey.helmvalues/default.yaml
    additionalValuesFiles:
      - valkey.helmvalues/hardened.yaml

labels:
  - pairs:
      app.kubernetes.io/name: valkey
    includeTemplates: true
    includeSelectors: true
