---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie

labels:
  - pairs:
      app.kubernetes.io/name: mealie
      app.kubernetes.io/instance: mealie
    includeTemplates: true
    includeSelectors: true

resources:
  - mealie.configuration.externalsecret.yaml
  - mealie.httproute.yaml
  - mealie.service.yaml
  - mealie.deployment.yaml
  - security/

images:
  # renovate: datasource=docker depName=ghcr.io/mealie-recipes/mealie
  - name: ghcr.io/mealie-recipes/mealie
    newTag: "v2.8.0"
