---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: crossplane # This must be commented out to prevent Kustomize from overriding the namespace in the ApplicationSet, ensuring it remains 'argocd'.

labels:
  - pairs:
      app.kubernetes.io/name: crossplane
      app.kubernetes.io/instance: crossplane
    includeTemplates: true
    includeSelectors: true

resources:
  - crossplane-secrets.namespace.yaml

  # Crossplane x ArgoCD
  - crossplane.applicationset.yaml

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/master/
    releaseName: crossplane
    namespace: crossplane
    version: 1.20.0-rc.0.140.g629ca2e2f
    valuesFile: crossplane.helmvalues/default.yaml
    additionalValuesFiles:
      - crossplane.helmvalues/hardened.yaml

transformers:
  - |
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: crossplane
      namespace: crossplane
    unsetOnly: true
