---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    # Source reference for argocd-extension-application-map
    source-ref.argocd.argoproj.io/0.path: defaults/kubernetes/kyverno/kustomize
    source-ref.argocd.argoproj.io/0.repository-url: https://github.com/chezmoidotsh/arcane.git
    source-ref.argocd.argoproj.io/0.target-revision: main
  name: kyverno
spec:
  destination:
    namespace: kyverno-system
    # server: {{ .server }}
  project: system
  sources:
    - ref: origin
      repoURL: https://github.com/chezmoidotsh/arcane.git
      targetRevision: main
      path: defaults/kubernetes/kyverno/kustomize

      kustomize:
        ignoreMissingComponents: true
        # components:
        #   - projects/{{ .name }}/src/infrastructure/kubernetes/kyverno/
        #   - projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/kyverno/

    - chart: kyverno
      helm:
        ignoreMissingValueFiles: true
        releaseName: kyverno
        valueFiles:
          - $origin/defaults/kubernetes/kyverno/helm/default.helmvalues.yaml
          # - $origin/projects/{{ .name }}/src/infrastructure/kubernetes/kyverno/override.helmvalues.yaml
          # - $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/kyverno/override.helmvalues.yaml
      repoURL: https://kyverno.github.io/kyverno/
      targetRevision: 3.6.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Delete=confirm
      - Prune=confirm
      - ServerSideApply=true
