---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tailscale-system

resources:
  # Required secrets and ProxyClass for Tailscale Operator
  - restricted.proxyclass.yaml
  - operator-oauth.externalsecret.yaml

  # Additional configuration for remote cluster resource access
  - remote-cluster.proxyclass.yaml
  - ts-dns.dnsconfig.yaml

  # Security policies (NetworkPolicies, PodSecurityStandards, etc.)
  - security/

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.94.1
    releaseName: tailscale-operator
    namespace: tailscale-system
    valuesFile: tailscale.helmvalues/default.yaml
    additionalValuesFiles:
      - tailscale.helmvalues/hardened.yaml
    valuesInline:
      operatorConfig:
        hostname: amiya-akn
    includeCRDs: true

generators:
  - # Protect some "private" information like internal IPs addresses.
    |-
    apiVersion: viaduct.ai/v1
    kind: ksops
    metadata:
      name: ksops
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: ksops
    files:
      - homelab.connector.yaml
