---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/description: |
      This ApplicationSet is responsible for automatically deploying all
      configurations across all clusters configured in ArgoCD. It achieves this
      by deploying an application that, in turn, deploys two other ApplicationSets:
      one for system/cluster applications and another for applications.
  name: shoot
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      annotations:
        # Source reference for argocd-extension-application-map
        source-ref.argocd.argoproj.io/0.path: projects/amiya.akn/src/argocd/shoot.apps
        source-ref.argocd.argoproj.io/0.repository-url: https://github.com/chezmoidotsh/arcane.git
        source-ref.argocd.argoproj.io/0.target-revision: main

      name: "{{ .name }}"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ regexReplaceAll "[^a-zA-Z0-9_-]" .name "-" }}'
      info:
        - name: Description
          value: >
            This ApplicationSet is responsible for automatically deploying all
            application and configurations for the cluster {{ .name }}.
      project: seed
      sources:
        - repoURL: https://github.com/chezmoidotsh/arcane.git
          path: projects/amiya.akn/src/argocd/shoot.apps
          targetRevision: main

          kustomize:
            patches:
              # This configuration ensures that cluster metadata is included in all ApplicationSets.
              # By doing so, it enables the dynamic templating of all related applications
              # using the associated cluster metadata, improving scalability and maintainability.
              - patch: |
                  - op: add
                    path: /spec/generators/0/matrix/generators/0/list/elements/-
                    value:
                      metadata:
                        annotations: {{ omit (.metadata.annotations | toYaml | fromYaml) "argocd.argoproj.io/tracking-id" | toYaml | nindent 8 }}
                        labels: {{ .metadata.labels | toYaml | nindent 8 }}
                      name: {{ .name | quote }}
                      nameNormalized: {{ .nameNormalized | quote }}
                      nameRFC1123: {{ regexReplaceAll "[^a-zA-Z0-9_-]" .name "-" | quote }}
                      server: {{ .server | quote }}
                  - op: add
                    path: /spec/template/metadata/labels
                    value: {}
                  - op: add
                    path: /spec/template/metadata/labels/argocd.argoproj.io~1cluster
                    value: {{ .name | quote }}
                target:
                  kind: ApplicationSet
                  name: system
              - patch: |
                  - op: add
                    path: /spec/generators/0/matrix/generators/0/list/elements/-
                    value:
                      metadata:
                        annotations: {{ omit (.metadata.annotations | toYaml | fromYaml) "argocd.argoproj.io/tracking-id" | toYaml | nindent 8 }}
                        labels: {{ .metadata.labels | toYaml | nindent 8 }}
                      name: {{ .name | quote }}
                      nameNormalized: {{ .nameNormalized | quote }}
                      nameRFC1123: {{ regexReplaceAll "[^a-zA-Z0-9_-]" .name "-" | quote }}
                      server: {{ .server | quote }}
                  - op: add
                    path: /spec/template/metadata/labels
                    value: {}
                  - op: add
                    path: /spec/template/metadata/labels/argocd.argoproj.io~1cluster
                    value: {{ .name | quote }}
                target:
                  kind: ApplicationSet
                  name: applications

              - patch: |
                  - op: add
                    path: /spec/generators/0/merge/generators/0/matrix/generators/0/git/directories/0/path
                    value: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/*
                  - op: add
                    path: /spec/generators/0/merge/generators/1/matrix/generators/0/git/files/0/path
                    value: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/*/.application.patch
                  - op: replace
                    path: /spec/generators/0/merge/generators/0/matrix/generators/1/list/elements/0
                    value:
                      .key: '{{ "{{ .path.basename }}" }}'
                      metadata:
                        annotations: {{ omit (.metadata.annotations | toYaml | fromYaml) "argocd.argoproj.io/tracking-id" | toYaml | nindent 8 }}
                        labels: {{ omit (.metadata.labels | toYaml | fromYaml) "app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/part-of" "app.kubernetes.io/version" | toYaml | nindent 8 }}
                      name: {{ .name | quote }}
                      nameNormalized: {{ .nameNormalized | quote }}
                      nameRFC1123: {{ regexReplaceAll "[^a-zA-Z0-9_-]" .name "-" | quote }}
                      server: {{ .server | quote }}
                  - op: add
                    path: /spec/template/metadata/labels
                    value: {}
                  - op: add
                    path: /spec/template/metadata/labels/argocd.argoproj.io~1cluster
                    value: {{ .name | quote }}
                target:
                  kind: ApplicationSet
                  name: system-new
              - patch: |
                  - op: add
                    path: /spec/generators/0/merge/generators/0/matrix/generators/0/git/directories/0/path
                    value: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/apps/*
                  - op: add
                    path: /spec/generators/0/merge/generators/1/matrix/generators/0/git/files/0/path
                    value: projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/apps/*/.application.patch
                  - op: replace
                    path: /spec/generators/0/merge/generators/0/matrix/generators/1/list/elements/0
                    value:
                      .key: '{{ "{{ .path.basename }}" }}'
                      metadata:
                        annotations: {{ omit (.metadata.annotations | toYaml | fromYaml) "argocd.argoproj.io/tracking-id" | toYaml | nindent 8 }}
                        labels: {{ omit (.metadata.labels | toYaml | fromYaml) "app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/part-of" "app.kubernetes.io/version" | toYaml | nindent 8 }}
                      name: {{ .name | quote }}
                      nameNormalized: {{ .nameNormalized | quote }}
                      nameRFC1123: {{ regexReplaceAll "[^a-zA-Z0-9_-]" .name "-" | quote }}
                      server: {{ .server | quote }}
                  - op: add
                    path: /spec/template/metadata/labels
                    value: {}
                  - op: add
                    path: /spec/template/metadata/labels/argocd.argoproj.io~1cluster
                    value: {{ .name | quote }}
                target:
                  kind: ApplicationSet
                  name: applications-new

              # This configuration ensures that the server field is set with the
              # cluster server URL for all applications.
              - patch: |
                  - op: add
                    path: /spec/destination/server
                    value: {{ .server | quote }}
                  - op: add
                    path: /metadata/labels
                    value: {}
                  - op: add
                    path: /metadata/labels/argocd.argoproj.io~1cluster
                    value: {{ .name | quote }}
                target:
                  kind: Application

              # These configuration ensures that the appropriate override values files are applied based
              # on the metadata of each cluster. This allows for consistent and automated deployment of
              # applications tailored to the specific requirements of each cluster environment.

              # - Cert-Manager
              - patch: |
                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ .name }}/src/infrastructure/kubernetes/cert-manager/override.helmvalues.yaml
                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/cert-manager/override.helmvalues.yaml
                target:
                  kind: Application
                  name: cert-manager

              - patch: |
                  - op: add
                    path: /spec/sources/0/kustomize/components
                    value:
                      - ../../../../projects/{{ .name }}/src/infrastructure/kubernetes/cert-manager
                      - ../../../../projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/cert-manager
                target:
                  kind: Application
                  name: cert-manager

              # - Envoy Gateway
              - patch: |
                  - op: add
                    path: /spec/sources/0/kustomize/components
                    value:
                      - ../../../../projects/{{ .name }}/src/infrastructure/kubernetes/envoy-gateway
                      - ../../../../projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/envoy-gateway

                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ .name }}/src/infrastructure/kubernetes/envoy-gateway/override.helmvalues.yaml
                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/envoy-gateway/override.helmvalues.yaml
                target:
                  kind: Application
                  name: envoy-gateway

              # - External-Secrets
              - patch: |
                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ .name }}/src/infrastructure/kubernetes/external-secrets/override.helmvalues.yaml
                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/external-secrets/override.helmvalues.yaml
                target:
                  kind: Application
                  name: external-secrets

              - patch: |
                  - op: add
                    path: /spec/sources/0/kustomize/components
                    value:
                      - ../../../../projects/{{ .name }}/src/infrastructure/kubernetes/external-secrets
                      - ../../../../projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/external-secrets


                  - op: add
                    path: /spec/sources/0/kustomize/patches
                    value:
                      - patch: |-
                          - op: add
                            path: /spec/provider/vault/auth/kubernetes/mountPath
                            value: {{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}
                          - op: add
                            path: /spec/provider/vault/auth/kubernetes/role
                            value: {{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}-eso-role
                        target:
                          kind: ClusterSecretStore
                          name: vault.chezmoi.sh
                target:
                  kind: Application
                  name: external-secrets

              # - Kyverno
              - patch: |
                  - op: add
                    path: /spec/sources/0/kustomize/components
                    value:
                      - ../../../../projects/{{ .name }}/src/infrastructure/kubernetes/kyverno
                      - ../../../../projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/kyverno

                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ .name }}/src/infrastructure/kubernetes/kyverno/override.helmvalues.yaml
                  - op: add
                    path: /spec/sources/1/helm/valueFiles/-
                    value: $origin/projects/{{ index .metadata.annotations "device.tailscale.com/hostname" | default .name }}/src/infrastructure/kubernetes/kyverno/override.helmvalues.yaml
                target:
                  kind: Application
                  name: kyverno

      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - Delete=confirm
          - Prune=confirm
          - ServerSideApply=true
