---
name: ‚ôªÔ∏è Refresh Trunk cache

on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: {}

jobs:
  trunk-cache:
    name: ‚ôªÔ∏è Refresh Trunk cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: ‚¨áÔ∏è Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: üì¶Ô∏è Populate cache with Trunk
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b # v1.2.4
        with:
          check-mode: populate_cache_only
