# Copyright 2024
#
# Everyone is permitted to copy, distribute, modify, merge, sell, publish,
# sublicense or whatever the fuck they want with this software but at their
# OWN RISK.
# The author has absolutely no fucking clue what the code in this project
# does. It might just fucking work or not, there is no third option.
#
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
---
name: ğŸ’š Validate OCI Image

on:
  workflow_call:
    inputs:
      application:
        description: Application to (re)build
        type: string
        required: true
      project:
        description: Project where the application is part of
        type: string
        required: true

env:
  ASDF_DIR: /home/runner/.asdf

permissions: {}

jobs:
  goss:
    name: âœ… Check '${{ inputs.project }}/${{ inputs.application }}' behavior
    permissions:
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # Install all required tools or restore them if the cache already exists
      - name: ğŸš§ Restore cached tools
        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: restore-asdf
        with:
          path: ${{ env.ASDF_DIR }}
          key: asdf-vm-${{ hashFiles('.tool-versions') }}
      - name: ğŸ“¦ï¸ Install required tools
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3.0.2
        with:
          skip_install: ${{ steps.restore-asdf.outputs.cache-hit == 'true' }}

      # Prepare the environment for the test
      - name: ğŸš§ Setup QEMU environment
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3.1.0
      - name: ğŸš§ Setup Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0
      - name: ğŸš§ Load `.envrc` context
        run: direnv allow && direnv exec / direnv export gha >> "${GITHUB_ENV}"

      # Run the tests
      - name: ğŸ‘· Task docker:images:build (localhost/${{ inputs.project }}/${{ inputs.application }}:ci)
        run: |
          task docker:images:build PROJECT=${{ inputs.project }} IMAGE=${{ inputs.application }} BUILD_TYPE=ci \
            --output group \
            --output-group-begin '::group::{{.TASK}} (${{ inputs.project }}/${{ inputs.application }})' \
            --output-group-end '::endgroup::'
        working-directory: apps/${{ inputs.project }}
      - name: ğŸ§ª Task docker:goss:run (localhost/${{ inputs.project }}/${{ inputs.application }}:ci)
        run: |
          echo '::group::docker:goss:run (${{ inputs.project }}/${{ inputs.application }})'
          task docker:ci PROJECT=${{ inputs.project }} IMAGE=${{ inputs.application }} GOSS_OPTS="--format junit" \
            > "images/${{ inputs.application }}/dist/ci/goss-report.xml"
          echo '::endgroup::'
        working-directory: apps/${{ inputs.project }}
      - name: ğŸ“ Upload Goss Test Report
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4.3.1
        if: always()
        with:
          check_name: Goss Test Report (${{ inputs.project }}/${{ inputs.application }})
          commit: ${{ github.event.workflow_run.head_sha }}
          include_passed: true
          report_paths: apps/${{ inputs.project }}/images/${{ inputs.application }}/dist/ci/goss-report.xml
