---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - network-policy.default-hardened.yaml
  - network-policy.allow-immich-from-envoy-gateway.yaml
  - network-policy.allow-immich-from-newt.yaml
  - network-policy.allow-immich-to-internet.yaml
  - network-policy.allow-immich-to-machine-learning.yaml
  - network-policy.allow-immich-to-sso.yaml
  - network-policy.allow-machine-learning-to-internet.yaml
  - network-policy.allow-postgres-from-cnpg.yaml
  - network-policy.allow-postgres-to-kubernetes-api.yaml
  - network-policy.allow-postgres-to-s3-backup.yaml
